use cs3380;

INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('22', 'City Hall', 'Assiniboia Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('67', 'Westdale via', 'Charleswood Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('60', 'Downtown', 'Pembina');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('75', 'University of Manitoba', 'Crosstown East');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('34', 'Downtown', 'McPhillips Super Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('30', 'Inkster Park', 'Inkster Park Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('75', 'Kildonan Place', 'Crosstown East');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('57', 'University of Winnipeg', 'Southdale Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('BLUE', 'University of Manitoba', 'Route BLUE');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('BLUE', 'Downtown', 'Route BLUE');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('691', 'Seel Station via Chevrier', 'Whyte Ridge');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('690', 'Kenaston via Fort Garry Industrial Park', 'Industrial');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('635', 'Misericordia Health Centre', 'Osborne Village');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('16', 'Island Lakes via Southdale Centre', 'Selkirk-Osborne');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('59', 'University of Winnipeg', 'South St. Anne''s Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('14', 'Ferry Road', 'Ellice-St. Mary''s');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('25', 'City Hall', 'Ness Super Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('31', 'City Hall', 'Keewatin Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('29', 'Logan via Sherbrook', 'Sherbrook - Stafford');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('29', 'Beaumont Station via Stafford', 'Sherbrook - Stafford');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('65', 'Downtown (City Hall)', 'Grant Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('28', 'Inkster Industrial Park', 'Brookside Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('10', 'St. Boniface via Provencher', 'St. Boniface-West Broadway');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('10', 'Wolseley via Tache', 'St. Boniface-West Broadway');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('10', 'St. Boniface via Tache', 'St. Boniface-West Broadway');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('10', 'Wolseley-Provencher via Provencher', 'St. Boniface-West Broadway');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('19', 'RRC Polytech via Notre Dame', 'Marion-Logan-Notre Dame');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('19', 'Windsor Park via Drake', 'Marion-Logan-Notre Dame');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('54', 'University of Winnipeg', 'St. Mary''s Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('58', 'City Hall', 'Dakota Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('41', 'Balmoral Station', 'Henderson Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('11', 'Polo Park', 'Portage-Kildonan');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('11', 'North Kildonan via Donwood', 'Portage-Kildonan');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('48', 'Balmoral Station', 'McMeans Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('96', 'St. Vital Centre', 'St. Vital Centre - Windsor Park');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('96', 'Paterson Loop via Southdale', 'St. Vital Centre - Windsor Park');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('49', 'North Transcona', 'Dugald');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('47', 'Transcona via Regent', 'Transcona - Pembina');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('47', 'University of Manitoba via Downtown', 'Transcona - Pembina');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('66', 'Downtown (City Hall)', 'Grant');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('19', 'RRC Polytech via Logan', 'Marion-Logan-Notre Dame');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('66', 'Unicity', 'Grant');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('19', 'Windsor Park via Autumnwood', 'Marion-Logan-Notre Dame');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('15', 'Airport via Wellington', 'Sargent-Mountain');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('15', 'Inkster Park via Inkster', 'Sargent-Mountain');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('18', 'Riverbend', 'North Main-Corydon');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('15', 'Mountain and Fife', 'Sargent-Mountain');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('77', 'Polo Park', 'Crosstown North');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('77', 'Kildonan Place', 'Crosstown North');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('43', 'Assiniboine', 'Munroe');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('694', 'Fort Garry Industrial Park via Wildwood', 'Wildwood');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('694', 'Seel Station via Wildwood', 'Wildwood');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('14', 'South St. Vital via Paddington', 'Ellice-St. Mary''s');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('18', 'Garden City Centre via Jefferson', 'North Main-Corydon');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('18', 'Tuxedo', 'North Main-Corydon');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('18', 'Corydon & Cambridge', 'North Main-Corydon');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('50', 'University of Winnipeg', 'Archibald');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('50', 'Sage Creek', 'Archibald');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('32', 'Downtown', 'North Main Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('32', 'via Leila', 'North Main Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('46', 'Balmoral Station', 'Transcona Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('16', 'Selkirk & McPhillips', 'Selkirk-Osborne');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('28', 'Oak Point Highway via Omands Creek', 'Brookside Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('45', 'Kildonan Place', 'Talbot');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('46', 'Transcona via Regent', 'Transcona Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('78', 'University of Manitoba', 'Waverley');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('78', 'Polo Park', 'Waverley');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('74', 'University of Manitoba', 'Kenaston');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('74', 'Polo Park', 'Kenaston');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('21', 'City Hall', 'Portage Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('21', 'Grace Hospital', 'Portage Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('75', 'Speers- Elizabeth', 'Crosstown East');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('42', 'Balmoral Station', 'Plessis Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('36', 'U of Manitoba', 'Northwest Super Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('41', 'North Kildonan', 'Henderson Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('17', 'Maples via', 'McGregor');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('635', 'Harkness Station', 'Osborne Village');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('17', 'Misericordia Health Centre', 'McGregor');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('11', 'Glenway', 'Portage-Kildonan');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('BLUE', 'St. Norbert', 'Route BLUE');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('55', 'St.Vital Centre via Meadowood', 'St. Anne''s');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('55', 'University of Winnipeg via Dakota', 'St. Anne''s');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('65', 'Ridgewood', 'Grant Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('91', 'Killarney', 'St. Norbert');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('91', 'St.Norbert', 'St. Norbert');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('60', 'University of Manitoba', 'Pembina');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('16', 'Tyndall Park via Manitoba', 'Selkirk-Osborne');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('23', 'City Hall via Sherbrook', 'Broadway - William');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('12', 'Polo Park', 'William');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('12', 'City Hall', 'William');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('35', 'City Hall', 'Maples Super Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('36', 'Health Sciences Centre', 'Northwest Super Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('693', 'Bridgwater Forest', 'Waverley Heights');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('693', 'Markham Station', 'Waverley Heights');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('47', 'Transcona via Kildare', 'Transcona - Pembina');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('32', 'Riverbend', 'North Main Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('676', 'Centre Street via Bridgwater', 'Bridgwater/River Road');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('676', 'St. Vital Centre via River Road', 'Bridgwater/River Road');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('89', 'North Transcona', 'North Transcona - Kildonan Place');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('89', 'Kildonan Place', 'North Transcona - Kildonan Place');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('66', 'Polo Park', 'Grant');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('11', 'North Kildonan via Rothesay', 'Portage-Kildonan');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('55', 'St. Vital Centre via Dakota', 'St. Anne''s');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('55', 'University of Winnipeg via Meadowood', 'St. Anne''s');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('36', 'Maples via Health Sciences Centre', 'Northwest Super Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('57', 'Southdale', 'Southdale Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('85', 'Kildonan Place', 'Kildonan Place - North Kildonan');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('43', 'Kildonan Place', 'Munroe');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('98', 'Grace Hospital', 'Westdale - Grace Hospital');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('98', 'Unicity', 'Westdale - Grace Hospital');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('672', 'University of Manitoba via Killarney', 'Killarney');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('672', 'Prairie Pointe via Killarney', 'Killarney');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('21', 'Crestview', 'Portage Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('46', 'Transcona via Kildare', 'Transcona Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('671', 'Prairie Pointe via Dalhousie', 'Dalhousie');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('671', 'University of Manitoba via Dalhousie', 'Dalhousie');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('21', 'St.Charles', 'Portage Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('58', 'South St. Vital via Southglen', 'Dakota Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('650', 'Whyte Ridge via Kenaston Common', 'McGillivray');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('650', 'Seel Station', 'McGillivray');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('58', 'South St. Vital via Paddington', 'Dakota Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('11', 'Henderson', 'Portage-Kildonan');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('35', 'Amber Trails', 'Maples Super Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('67', 'City Hall', 'Charleswood Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('33', 'Maples via Jefferson', 'Maples');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('22', 'St.Charles', 'Assiniboia Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('33', 'Downtown', 'Maples');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('33', 'Maples via Mapleglen', 'Maples');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('25', 'Unicity', 'Ness Super Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('16', 'Tyndall Park via Burrows', 'Selkirk-Osborne');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('16', 'Plaza Dr via St. Vital Centre', 'Selkirk-Osborne');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('40', 'All Seasons', 'All Seasons Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('44', 'Kildonan Place via London', 'Grey');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('71', 'Templeton via Sinclair', 'Arlington');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('71', 'Portage via McPhillips', 'Arlington');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('77', 'Garden City Centre', 'Crosstown North');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('34', 'Maples', 'McPhillips Super Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('30', 'Downtown', 'Inkster Park Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('20', 'Watt & Leighton', 'Academy-Watt');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('20', 'Airport Terminal', 'Academy-Watt');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('20', 'Henderson', 'Academy-Watt');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('21', 'Westwood', 'Portage Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('79', 'Westdale via Kenaston', 'Charleswood');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('79', 'Polo Park via Kenaston', 'Charleswood');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('44', 'Kildonan Place via Louelda', 'Grey');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('44', 'Broadway via London', 'Grey');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('17', 'Amber Trails', 'McGregor');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('17', 'Garden City Centre', 'McGregor');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('677', 'Kenaston Common via Industrial Park', 'Wilkes');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('677', 'Beaumont station via Industrial Park', 'Wilkes');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('24', 'Unicity', 'Ness Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('24', 'City Hall', 'Ness Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('15', 'Inkster Park via Church', 'Sargent-Mountain');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('15', 'Airport via Flight Road', 'Sargent-Mountain');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('15', 'Mountain & Fife', 'Sargent-Mountain');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('49', 'Balmoral Station', 'Dugald');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('48', 'North Transcona', 'McMeans Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('22', 'Westwood', 'Assiniboia Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('31', 'Meadows West', 'Keewatin Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('28', 'City Hall', 'Brookside Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('88', 'Fife', 'Inkster Industrial Park - Scotia');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('88', 'Cathedral & Main', 'Inkster Industrial Park - Scotia');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('662', 'Markham Station via Richmond West', 'Richmond');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('662', 'University of Manitoba via Richmond West', 'Richmond');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('79', 'Portage & Tylehurst via Kenaston', 'Charleswood');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('90', 'Henderson & Whellams', 'Kildonan Place - Whellams Lane');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('90', 'North Transcona', 'Kildonan Place - Whellams Lane');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('22', 'Crestview', 'Assiniboia Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('54', 'St. Amant', 'St. Mary''s Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('87', 'Beghin & Dugald', 'Industrial');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('87', 'Crossroads Station', 'Industrial');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('86', 'South Transcona', 'Mission Gardens');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('14', 'South St. Vital via Dakota', 'Ellice-St. Mary''s');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('42', 'Lakeside Meadows', 'Plessis Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('649', 'Whyte Ridge via Chevrier', 'Chevrier');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('649', 'Windermere via Pembina', 'Chevrier');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('19', 'Elizabeth & Drake', 'Marion-Logan-Notre Dame');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('59', 'Island Lakes', 'South St. Anne''s Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('41', 'Glenway', 'Henderson Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('26', 'City Hall', 'Logan - Berry');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('85', 'Henderson & Whellams', 'Kildonan Place - North Kildonan');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('23', 'Fort and Assiniboine via Maryland', 'Broadway - William');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('40', 'Balmoral Station', 'All Seasons Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('55', 'St. Anne''s & Niakwa', 'St. Anne''s');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('68', 'River Heights via Wellington Crescent', 'Grosvenor');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('68', 'Downtown', 'Grosvenor');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('83', 'Thompson & Ness', 'Unicity - Strauss Dr - Murray Industrial Park');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('83', 'Unicity', 'Unicity - Strauss Dr - Murray Industrial Park');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('16', 'St.Vital Centre', 'Selkirk-Osborne');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('16', 'Southdale Centre', 'Selkirk-Osborne');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('26', 'Polo Park', 'Logan - Berry');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('26', 'Portage & Tylehurst', 'Logan - Berry');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('14', 'St. Mary''s & Dakota', 'Ellice-St. Mary''s');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('97', 'Point Douglas', 'Inkster Industrial Park - Point Douglas');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('97', 'Fife', 'Inkster Industrial Park - Point Douglas');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('15', 'Downtown', 'Sargent-Mountain');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('95', 'Riverview', 'Tuxedo - Riverview');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('95', 'Polo Park', 'Tuxedo - Riverview');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('56', 'Downtown', 'St. Boniface');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('56', 'St. Boniface', 'St. Boniface');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('38', 'Templeton & McPhillips', 'Salter');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('38', 'The Forks', 'Salter');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('690', 'Seel Station via Fort Garry Industrial Park', 'Industrial');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('691', 'Whyte Ridge via Scurfield', 'Whyte Ridge');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('59', 'Aldgate', 'South St. Anne''s Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('18', 'Assiniboine Park', 'North Main-Corydon');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('31', 'Oak Point', 'Keewatin Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('46', 'Plessis & Regent', 'Transcona Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('53', 'Downtown', 'Norwood');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('53', 'Norwood', 'Norwood');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('50', 'Windsor Park', 'Archibald');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('45', 'Downtown', 'Talbot');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('44', 'Broadway via Louelda', 'Grey');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('11', 'City Hall', 'Portage-Kildonan');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('93', 'Highbury & Southfields', 'South St. Vital - St. Marys');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('93', 'St. Vital Centre', 'South St. Vital - St. Marys');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('66', 'Grant & Kenaston', 'Grant');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('71', 'Portage via Sinclair', 'Arlington');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('71', 'WalMart via McPhillips', 'Arlington');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('75', 'Lakewood at Vermillion', 'Crosstown East');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('677', 'Outlet Mall via Wilkes', 'Wilkes');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('24', 'Portage & Tylehurst', 'Ness Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('44', 'London & Munroe via London', 'Grey');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('90', 'Kildonan Place', 'Kildonan Place - Whellams Lane');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('20', 'Fort & Portage', 'Academy-Watt');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('11', 'Westwood', 'Portage-Kildonan');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('47', 'Kildonan Place', 'Transcona - Pembina');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('77', 'Red River College', 'Crosstown North');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('11', 'St. Charles', 'Portage-Kildonan');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('11', 'Crestview', 'Portage-Kildonan');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('68', 'Stradbrook & Osborne', 'Grosvenor');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('83', 'Murray Park', 'Unicity - Strauss Dr - Murray Industrial Park');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('16', 'Kingston Row', 'Selkirk-Osborne');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('66', 'Dieppe Loop', 'Grant');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('24', 'Polo Park', 'Ness Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('83', 'Portage & Ronald', 'Unicity - Strauss Dr - Murray Industrial Park');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('95', 'Shaftesbury Park', 'Tuxedo - Riverview');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('10', 'Downtown', 'St. Boniface-West Broadway');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('82', 'Unicity', 'Grace Hospital - Unicity');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('82', 'Grace Hospital', 'Grace Hospital - Unicity');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('83', 'Grace Hospital', 'Unicity - Strauss Dr - Murray Industrial Park');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('83', 'Crestview & Ashern', 'Unicity - Strauss Dr - Murray Industrial Park');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('642', 'Fort Garry Industrial Park via Lindenwoods East', 'Lindenwoods East');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('642', 'Seel Station via Lindenwoods East', 'Lindenwoods East');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('641', 'Beaumont Station via Lindenwoods West', 'Lindenwoods West');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('641', 'Kenaston via Lindenwoods West', 'Lindenwoods West');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('49', 'Dugald & Beghin', 'Dugald');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('55', 'St.Anne''s & Beliveau', 'St. Anne''s');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('54', 'South St. Vital', 'St. Mary''s Express');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('17', 'Seven Oaks Hospital', 'McGregor');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('98', 'Westdale', 'Westdale - Grace Hospital');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('19', 'Notre Dame & Arlington', 'Marion-Logan-Notre Dame');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('92', 'Crossroads Station', 'Crossroads Station - Lakeside Meadows');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('92', 'Lakeside Meadows', 'Crossroads Station - Lakeside Meadows');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('92', 'Kildonan Place', 'Crossroads Station - Lakeside Meadows');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('33', 'McPhillips & Mapleglen', 'Maples');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('77', 'Whellams Lane', 'Crosstown North');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('87', 'South Transcona', 'Industrial');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('86', 'Crossroads Station', 'Mission Gardens');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('18', 'Main & Templeton', 'North Main-Corydon');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('10', 'Wolseley via Provencher', 'St. Boniface-West Broadway');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('19', 'Downtown', 'Marion-Logan-Notre Dame');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('662', 'Killarney & Pembina', 'Richmond');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('44', 'London & Munroe via Louelda', 'Grey');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('45', 'Munroe & Prevette', 'Talbot');
INSERT INTO Bus_Route (Route_Number, Route_Destination, Route_Name) VALUES ('50', 'Speers - Elizabeth', 'Archibald');
