INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('River Park South', 4000);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Dakota Crossing', 3766);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Rossmere-A', 3643);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Tyndall Park', 3564);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Windsor Park', 3443);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('The Maples', 3353);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Chalmers', 3256);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Jefferson', 2977);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('River East', 2936);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Fort Richmond', 2906);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Canterbury Park', 2905);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Linden Woods', 2811);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Wolseley', 2685);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Crestview', 2659);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('King Edward', 2648);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Westwood', 2647);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Daniel McIntyre', 2628);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('St. John''s', 2619);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Sage Creek', 2540);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Peguis', 2455);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Whyte Ridge', 2408);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Sargent Park', 2393);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Munroe East', 2380);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Minto', 2324);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Island Lakes', 2281);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Richmond West', 2254);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('William Whyte', 2251);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('North River Heights', 2249);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Kildare-Redonda', 2227);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Valley Gardens', 2193);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Lord Roberts', 2146);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Amber Trails', 2144);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Meadows', 2060);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Southdale', 2042);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Springfield North', 2033);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Garden City', 2027);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('South Pointe', 1995);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Glenwood', 1975);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Weston', 1965);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Burrows Central', 1932);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Meadowood', 1847);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Robertson', 1791);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('St. Matthews', 1745);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Riverbend', 1744);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Royalwood', 1739);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Silver Heights', 1678);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Prairie Pointe', 1665);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Mandalay West', 1660);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Waverley Heights', 1660);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Rossmere-B', 1649);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Templeton-Sinclair', 1639);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Riverview', 1619);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Central St. Boniface', 1596);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Kildonan Drive', 1581);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Norwood East', 1580);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Deer Lodge', 1578);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Minnetonka', 1574);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Elmhurst', 1542);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Earl Grey', 1535);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Westdale', 1534);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Inkster-Faraday', 1519);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Inkster Gardens', 1516);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Betsworth', 1508);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Mission Gardens', 1458);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Pulberry', 1413);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Bridgwater Trails', 1393);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('East Elmwood', 1377);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Grassie', 1376);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Radisson', 1355);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Seven Oaks', 1311);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Central River Heights', 1288);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('West Alexander', 1274);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Bridgwater Forest', 1252);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Munroe West', 1240);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Sir John Franklin', 1220);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Rockwood', 1220);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Booth', 1216);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Buchanan', 1196);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Bridgwater Lakes', 1194);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('St. George', 1189);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Brooklands', 1159);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Fraipont', 1158);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Heritage Park', 1131);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Victoria West', 1098);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Norwood West', 1086);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Worthington', 1044);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Maybank', 1038);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Talbot-Grey', 980);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('South River Heights', 978);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Varsity View', 966);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Crescentwood', 964);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Luxton', 964);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Sturgeon Creek', 962);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Beaumont', 962);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Shaughnessy Park', 934);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Glenelm', 931);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Eric Coy', 909);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Kirkfield', 900);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('North Point Douglas', 883);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Tuxedo', 880);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('South Tuxedo', 846);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Crescent Park', 839);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('North Inkster Industrial', 825);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Spence', 817);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Parc La Salle', 813);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Point Road', 799);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Ridgewood South', 789);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('McMillan', 785);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Fairfield Park', 770);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('St. James Industrial', 764);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Niakwa Place', 763);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Margaret Park', 735);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Melrose', 714);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Centennial', 713);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Leila-McPhillips Triangle', 709);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('West Broadway', 708);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('St. Vital Perimeter South', 696);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('North St. Boniface', 687);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Kern Park', 683);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('West Kildonan Industrial', 680);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Dufferin', 679);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Rivergrove', 675);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Elm Park', 674);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Bruce Park', 664);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Richmond Lakes', 623);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Wellington Crescent', 607);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Rosser-Old Kildonan', 560);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Norberry', 557);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('St. Boniface Industrial Park', 557);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Varennes', 547);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Jameswood', 542);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Vista', 536);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Mathers', 522);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Maginot', 520);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Springfield South', 516);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('River West Park', 507);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Grant Park', 491);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Eaglemere', 483);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('St. Norbert', 475);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('J. B. Mitchell', 469);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Burrows-Keewatin', 459);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Normand Park', 450);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Leila North', 441);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Southland Park', 435);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Bridgwater Centre', 426);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Linden Ridge', 419);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Glendale', 408);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Wildwood', 405);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Roblin Park', 403);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Ebby-Wentworth', 395);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Archwood', 389);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Inkster Industrial Park', 384);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Mynarski', 376);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('River-Osborne', 376);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Woodhaven', 351);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Old Tuxedo', 336);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Birchwood', 330);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('South Portage', 302);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Southboine', 302);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Wilkes South', 294);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Ridgedale', 286);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Lavalee', 279);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Vialoux', 277);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Transcona South', 262);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Mission Industrial', 259);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Montcalm', 257);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Lord Selkirk Park', 249);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Assiniboia Downs', 247);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Logan-C.P.R.', 235);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Marlton', 233);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Kingston Crescent', 227);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Victoria Crescent', 227);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Exchange District', 225);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Stock Yards', 218);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('St. John''s Park', 199);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Dufresne', 192);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Tuxedo Industrial', 190);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Transcona North', 187);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Chevrier', 187);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Agassiz', 180);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Niakwa Park', 169);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('South Point Douglas', 167);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Waverley West B', 162);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Brockville', 159);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Regent', 142);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Oak Point Highway', 136);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Broadway-Assiniboine', 132);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Kensington', 131);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('West Fort Garry Industrial', 129);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Armstrong Point', 127);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('University', 127);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Kil-Cona Park', 126);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Assiniboine Park', 121);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Dufferin Industrial', 121);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Dugald', 115);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Central Park', 112);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Tyne-Tees', 108);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Valhalla', 107);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Edgeland', 97);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Roslyn', 91);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Omand''s Creek Industrial', 89);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Holden', 86);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Polo Park', 85);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Airport', 85);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Pacific Industrial', 82);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Portage-Ellice', 80);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Kildonan Crossing', 79);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Pembina Strip', 79);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Cloutier Drive', 71);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('McLeod Industrial', 65);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Murray Industrial Park', 63);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Buffalo', 62);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Alpine Place', 56);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('West Wolseley', 55);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Tissot', 53);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Civic Centre', 50);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('China Town', 45);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Weston Shops', 42);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Legislature', 41);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Transcona Yards', 40);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Turnbull Drive', 40);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Colony', 37);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Portage & Main', 34);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Symington Yards', 34);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Perrault', 26);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('The Forks', 23);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Saskatchewan North', 22);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Trappistes', 22);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('La Barriere', 19);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('St. Vital Centre', 16);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Griffin', 16);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Parker', 9);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('North Transcona Yards', 8);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Kildonan Park', 5);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('West Perimeter South', 3);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('The Mint', 3);
INSERT INTO Neighbourhood (Neighbourhood_Name, Number_Of_Houses) VALUES ('Maple Grove Park', 2);
