INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P13Fire Hydrant', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P12L/Z Overtime', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P16No Park', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P14Improperly Parking', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P19Crosswalk (MRKD/UNMRKD)', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P17Too close to a traffic sign', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P03Rush Hour', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P06No Stop', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('MP20-Parked on a Boulevard', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('MP06-No Stop', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('MP16-No Park', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P09Too close/in an intersection', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('MP24-Wrong Direction', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P30Designated space', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P26Fire Lane', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P01Meter Expired', 60.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P20Parked on a Boulevard', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P54Abandoned/derelict', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P21Obstructing- vehicle', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P15Alley', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P02Meter Overtime', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P24Wrong Direction', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P04Oversized Vehicle', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P22Wrong side of Rd', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P64No Stop/Park in a taxi stand', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P07Disabled L/Z', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P18Side walk', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P25Blocking bike/ped path', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P11L/Z no activity', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P08L/Z/Disabled-Invalid permit', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P10Blocked driveway', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P39Snow Route', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P58Unplated/unregistered', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P28No Prk/Stop St.Work/Spec.EVNT', 150.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P62Veh.on priv.prop-Rule__', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P05Overtime', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('MP26-Fire Lane', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('MP03-Rush Hour', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('MP23-Double Parked', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('MP25-Blocking bike/ped path', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P65Extended Snow Route', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('MP22-Wrong side of Rd', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P51Electrical Cord', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P23Double Parked', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P29To close to Railway', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P52Repair Vehicle', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P37RPB Zone', 150.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('MP39Snow Route', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P53Obstruct desgn. space/Dis L/Z', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P55Advertised Vehicle', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('15Alley', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P40Mob Vendor-No permit', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P27Fire-Obstructing', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('07 No stopping anytime', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('27 2006 No stopping 07:00 - 09:0', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('01 2006 Parked -meter expi', 40.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('38 2010 Overtime Parking', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('08 No parking anytime', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('09 No parking in alley', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('MP37-RPB Zone', 200.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P37-RPB Zone', 200.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('17 Parking on boulevard', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P31Bus Parking', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P34Unlawful display-Invalid prmt', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P37RPB', 200.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('21 Double parked', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('06 No stopping - bus stop', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('18 Park within 9 metres of traff', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P33Permit restriction', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('10 No parking - street work', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P36False info-Invalid permit', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('14 2008 Improperly parked', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('20 2008 Park within 3 meters cur', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('23 2008 Parking to obstruct traf', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('13 No parking - taxi stand', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('11 No parking - loading zone', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('01 2011 Parked -meter expi', 60.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('33 2011 Stand/stop/park on snow', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('15 2008 Parked on a Sidewalk', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('28 2006 No stopping 15:30- 17:30', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('24 2008 Park on Crosswalk', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('32 2008 Disabled - No Park/Stop', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('12 No parking - limited times', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('34 2011 Stand/stop/park in resid', 150.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('02 2011 Meter overtime parking', 60.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('16 Park within 3 metres of appro', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('29 No parking - private property', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('42 2011 Stand/stop/park on snow', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('31 2008 Fire Lane - No Park/Stop', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('35 2012 Abandoned veh on street', 400.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('22 Park in front of driveway', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('01Meter Expired', 60.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('12L/Z Overtime', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('13Fire Hydrant', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('06No Stop', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('05Overtime', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('18Side walk', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('03Rush Hour', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('16No Park', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('02Meter Overtime', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('31Bus Parking', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('04Oversized Vehicle', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('22Wrong side of Rd', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('14Improperly Parking', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('30Designated space', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('20Parked on a Boulevard', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('19Crosswalk (MRKD/UNMRKD)', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('09Too close/in an intersection', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('28No Prk/Stop St.Works/Spec.EVNT', 150.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('17Too close to a traffic sign', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('39Snow Route', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('37RPB Zone', 150.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('38Declared Snow Route', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('24Wrong Direction', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('M06-No Stop', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('M26-Fire Lane', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('51Electrical Cord', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P38Declared Snow Route', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P48Mobile Vendor-20m from estbmt', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P56Vehicle for Sale', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('MP05- Overtime', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('34 2008 Park/stop on non-snow ro', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('33 2008 park/stop on snow route', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P54Abandoned/inoperable', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P67 No park/stop carshare', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('30 2008 Park/Stop Snow Emergency', 200.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('M16-No Park', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('54Abandoned/derelict', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('M24-Wrong Direction', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('26 Overnight parking', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('MP68Extended Winter Route', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('36 2010 Parked/wrong side res st', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('32 No parking/No stopping - hand', 150.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('M23-Double Parked', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('05 Parked at hooded meter', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('02 Meter overtime parking', 50.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('19 2008 Parked within Intersecti', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('25 Parked too far from curb', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('03 Improperly parked at meter', 50.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('37 2010 Advertised/veh parked st', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('03 2011 Improperly parked at met', 60.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('40 2012 Repair Vehicle on Street', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('41 2012 Place or leave unattende', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('21Obstructing- vehicle', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('62Veh.on priv.prop-Rule__', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('11L/Z no activity', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('26Fire Lane', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('07Disabled L/Z', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('10Blocked driveway', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('56Vehicle for Sale', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('55Advertised Vehicle', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('52Repair Vehicle', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('08L/Z/Disabled-Invalid permit', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('40Mob Vendor-No permit', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('23Double Parked', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('32Invalid permit', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('25Blocking bike/ped path', 0.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('63Invalid physical permit', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('M22-Wrong side of Rd', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('M20-Parked on a Boulevard', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('27Fire-Obstructing', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('M25-Blocking bike/ped path', 0.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('58Unplated/unregistered', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('45Mobile Vndor 3m of ent.to bldg', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('M39Snow Route', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('64No Stop/Park in a taxi stand', 70.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P32Invalid permit', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P49Removed mark', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P47Serve cust located on rdwy', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P41Mobile Vendor Permit restrict', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P45Mobile Vndr 3m of ent.to bldg', 300.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('MP69Annual Winter Route', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P69Annual Winter Route', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P68Extended Winter Route', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P60Dischrg waste material on st.', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P59Washing VEH on street', 100.0);
INSERT INTO Parking_Violation (Violation_Type, Fine_Amount) VALUES ('P61Depos slug/obj.in prkg meter', 300.0);
